### ISSUE TITLE
Upgrade to Material-UI beta.9

### ISSUE THREAD

**Issue by cr101** [OrigenStudio/portfolio#9]
[Material-UI v1.0.0-beta.9](https://github.com/callemall/material-ui/releases/tag/v1.0.0-beta.9) was released today. See if the latest beta will help with the CSS loading delay

**Comment by oliviertassinari** [comment]
I'm looking into adding a Gatsby example in Material-UI. I think that I will start with this project.

**Comment by PolGuixe** [comment]
@oliviertassinari cool! How we can help?

**Comment by oliviertassinari** [comment]
@PolGuixe Ok. I was able to get something stable following the Next.js example: https://github.com/mui-org/material-ui/pull/9779.
